### PR TITLE
Update jslint-core.js to Crockford's latest jslint.js

### PR DESCRIPTION
**Pull request by csexton**
This fixes the errors seen in MacVim on Lion. And hopefully #26 in the process.

### CODE REVIEW

**Comment by techfola** [comment]
This fixed issues I was having after updating Snow Leopard to 10.6.8 as well.  Thanks!

**Comment by bryanchow** [comment]
I don't know about OS X Lion, but I can confirm that this fixed JSLint no working after updating Snow Leopard to 10.6.8 for me too. Thanks, csexton.

**Comment by VAggrippino** [comment]
This breaks jslint.vim for anyone using node.js because of 150+ lines of code in the original jslint-core.js that make it work with node.js.  It's all for setting properties of the exports object that node.js needs.

Also see https://github.com/hallettj/jslint.vim/issues/13#issuecomment-1872871

## 

Ghodmode
http://www.ghodmode.com/blog

**Comment by hallettj** [comment]
Thank you for contributing this fix!  I finally got around to pulling in the latest version of jslint, and fixing node.js compatibility.

**Pull request closed without merging**
